local:
  env: 'local'
  root_data_path: '/Users/Onur/opt/MLrepos/shop_sales_prediction/data'
  fn_categories: 'category_list.csv'
  fn_items: 'item_list.csv'
  fn_shops: 'shop_list.csv'
  fn_transactions: 'transaction.csv'
  fn_test: 'test.csv'
  fn_train_base: 'train_base.parquet'
  fn_train_ts: 'train_ts.parquet'
  fn_val_base: 'val_base.parquet'
  fn_val_ts: 'val_ts.parquet'